server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: po0132stgres
    url: jdbc:postgresql://185.133.152.172:5432/catherine
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true